---
- name: Symlink .zshrc
  ansible.builtin.file:
    src: "~/.dotfiles/zsh/.zshrc"
    dest: "~/.zshrc"
    state: link
  become_user: "{{ username }}"

- name: Set ZSH as default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
