---
- name: Symlink .zshrc
  ansible.builtin.file:
    src: "~/.dotfiles/zsh/.zshrc"
    dest: "~/.zshrc"
    state: link
  become_user: geloman

- name: Clone oh-my-zsh
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "~/.oh-my-zsh"
    clone: true
    depth: 1
  become_user: geloman

- name: Set ZSH as default shell
  ansible.builtin.user:
    name: geloman
    shell: /usr/bin/zsh
