#!/bin/sh

apt update -y && apt upgrade -y
apt install -y zsh neovim eza fzf ripgrep fd-find bat git-delta gcc tar unzip curl wget neofetch

useradd --create-home --groups sudo --shell /usr/bin/zsh geloman
mkdir -p /home/geloman/{.config,.personal,.development}

git clone --depth 1 https://github.com/geloman-likes-rust/dotfiles /home/geloman/.dotfiles
git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git /home/geloman/.oh-my-zsh

ln /home/geloman/.dotfiles/zsh/.zshrc /home/geloman/.zshrc
ln /home/geloman/.dotfiles/nvim /home/geloman/.config/
ln /home/geloman/.dotfiles/tmux/.tmux.conf /home/geloman/.tmux.conf

$(command -v nvim) --headless "+Lazy! restore" +qa
