---
- name: Install common packages
  ansible.builtin.apt:
    name:
      - eza
      - ripgrep
      - fd-find
      - bat
      - git-delta
      - make
      - gcc
      - tar
      - unzip
      - curl
      - wget
      - jq
      - shfmt
      - neofetch
      - ansible
      - pylint
      - yamllint
      - ansible-lint
      - shellcheck
      - luarocks
    state: latest

- name: Symlink batcat to bat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
