---
- name: Install common packages
  ansible.builtin.apt:
    name:
      - eza
      - ripgrep
      - fd-find
      - bat
      - git-delta
      - vim
      - universal-ctags
      - direnv
      - make
      - gcc
      - tar
      - unzip
      - curl
      - wget
      - jq
      - pipx
      - shfmt
      - neofetch
      - ansible
      - pylint
      - yamllint
      - ansible-lint
      - shellcheck
      - luarocks
    state: latest

- name: Symlink batcat to bat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link

- name: Install uv (python package manager)
  ansible.builtin.shell:
    cmd: pipx install uv
  become_user: "{{ username }}"
