---
- name: Install lazygit
  ansible.builtin.shell:
    cmd: "GOPATH=~/.go go install github.com/jesseduffield/lazygit@latest"
    creates: "~/.go/bin/lazygit"
  become_user: "{{ username }}"

- name: Symlink lazygit config
  ansible.builtin.file:
    src: "~/.dotfiles/lazygit"
    dest: "~/.config/lazygit"
    state: link
  become_user: "{{ username }}"
