---
- name: Ensure tmux is installed
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Symlink tmux configuration file
  ansible.builtin.file:
    src: "~/.dotfiles/tmux/.tmux.conf"
    dest: "~/.tmux.conf"
    state: link
  become_user: "{{ username }}"
