---
- name: Symlink .gitconfig
  ansible.builtin.file:
    src: "~/.dotfiles/.gitconfig"
    dest: "~/.gitconfig"
    state: link
  become_user: "{{ username }}"

- name: Git Pull Dotfiles Changes on Reboot
  ansible.builtin.cron:
    name: git pull dotfiles @reboot
    special_time: reboot
    job: "git -C ~/.dotfiles pull --rebase"
  become_user: "{{ username }}"
