---
- hosts: all
  become: yes
  vars:
    username: gelocraft
  pre_tasks:
    - name: Update and Upgrade packages
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        create_home: true

    - name: Clone user dotfiles
      ansible.builtin.git:
        repo: "https://github.com/gelocraft/dotfiles"
        dest: "~/.dotfiles"
      become_user: "{{ username }}"

  roles:
    - common
    - stylua
    - docker
    - minikube
    - terraform
    - git
    - zsh
    - tmux
    - neovim
    - nodejs
    - golang
    - lsp
