---
- hosts: all
  become: true
  vars:
    username: gelocraft
    dotfiles_repo: "gelocraft/dotfiles"
  pre_tasks:
    - name: Update and Upgrade packages
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        create_home: true

    - name: Clone user dotfiles
      ansible.builtin.git:
        repo: "https://github.com/{{ dotfiles_repo }}"
        dest: "~/.dotfiles"
      become_user: "{{ username }}"

    - name: Change Remote Url of Dotfiles
      ansible.builtin.shell:
        cmd: >
          "git -C ~/.dotfiles remote set-url
          origin git@github.com:{{ dotfiles_repo }}.git"
      become_user: "{{ username }}"

    - name: Git Pull Dotfiles Changes on Reboot
      ansible.builtin.cron:
        name: git pull dotfiles @reboot
        special_time: reboot
        job: "git -C ~/.dotfiles pull --rebase"
      become_user: "{{ username }}"

    - name: Create ssh directory
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: "0755"
      become_user: "{{ username }}"

    - name: Symlink ssh config
      ansible.builtin.file:
        path: "~/.dotfiles/ssh/config"
        desc: "~/.ssh/config"
        state: link
      become_user: "{{ username }}"

  roles:
    - common
    - stylua
    - docker
    - minikube
    - terraform
    - git
    - zsh
    - tmux
    - neovim
    - nodejs
    - golang
    - starship
    - lazygit
    - fzf
    - lsp
