---
- hosts: all
  become: true
  vars:
    username: gelocraft
    dotfiles_repo: "gelocraft/dotfiles"
  pre_tasks:
    - name: Update and Upgrade packages
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        upgrade: safe
        update_cache: true

    - name: "Create User {{ username }}"
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        create_home: true

    - name: "Delete default password of {{ username }}"
      ansible.builtin.shell: "passwd --delete {{ username }}"

    - name: Clone user dotfiles
      ansible.builtin.git:
        repo: "https://github.com/{{ dotfiles_repo }}"
        dest: "~/.dotfiles"
      become_user: "{{ username }}"

  roles:
    - common
    - stylua
    - docker
    - minikube
    - terraform
    - git
    - zsh
    - tmux
    - neovim
    - nodejs
    - golang
    - starship
    - lazygit
    - fzf
    - lsp
