- hosts: all
  become: yes
  pre_tasks:
    - name: Update and Upgrade packages
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Create User
      ansible.builtin.user:
        name: geloman
        groups: sudo
        create_home: true

    - name: Clone user dotfiles
      ansible.builtin.git:
        repo: "https://github.com/gelocraft/dotfiles"
        dest: "~/.dotfiles"
      become_user: geloman

    - name: Change dotfiles remote origin
      ansible.builtin.git:
        repo: "git@github.com:geloman-likes-rust/dotfiles"
        dest: "~/.dotfiles"
        remote: origin
        clone: no
        update: no
      become_user: geloman

  roles:
    - common
    - stylua
    - docker
    - minikube
    - terraform
    - git
    - zsh
    - tmux
    - neovim
    - nodejs
    - golang
    - lsp
