name: Ansible Lint

on:
  workflow_dispatch:
  push:
    paths:
      - ansible/*

defaults:
  run:
    working-directory: ./ansible

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@main
      - name: Yaml Lint
        run:
          yamllint .
