---
name: Create Machine Image

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      release_tag:
        description: release tag
        type: choice
        default: v0.2.1
        options:
          - main
          - v0.2.1
          - v0.2.0
          - v0.1.1
          - v0.1.0

defaults:
  run:
    working-directory: ./packer

jobs:
  packer:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_tag }}

      - uses: hashicorp/setup-packer@main

      - name: Create Machine Image
        run: |
          packer init .
          packer build .
