name: Terraform Lint

on:
  push:
    paths:
      - terraform/*

defaults:
  run:
    working-directory: ./terraform

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Lint
        run: terraform fmt -check
