name: Yaml Lint

on:
  workflow_dispatch:
  push:
    paths:
      - ansible/*

defaults:
  run:
    working-directory: ./ansible

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Yaml Lint
        run: yamllint .
